<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastFood.Domain\FastFood.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Extensions\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Jobs\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Services\" />
    <Folder Include="Common\Security\" />
    <Folder Include="Common\Response\" />
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
